### ISSUE TITLE
Certs marked as valid on matrix.example.org, but invalid on example.org

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-federation-tester#27] opened 2019-02-06 18:48 UTC
Testing `matrix.snopyta.org`, we get `ValidCertificates` == `true`, but testing `snopyta.org` gives `false`.

Well-known seems to be set up correctly, so this doesn't make much sense.

#26 may be the cause however.

**Comment by tulir** [comment] 2019-02-13 21:40
This does not seem to be fixed by matrix-org/gomatrixserverlib#109.

**Comment by richvdh** [comment] 2019-02-13 21:41
indeed. the problem is not the parsing of the port (as per #26), but the fact that it is looking for the wrong server name in the certificate. it looks like #35 fixes this

**Comment by richvdh** [comment] 2019-02-13 23:25
https://matrix.org/federationtester/api/report?server_name=snopyta.org now gives `"ValidCertificates": true` \o/

**Closed by richvdh** 2019-02-13 23:25 UTC
