### ISSUE TITLE
Test both ipv6 and ipv4 for .well-known request

### ISSUE THREAD

**Issue by stygianguest** [matrix-org/matrix-federation-tester#83] opened 2019-04-24 08:14 UTC
I've had several problems due to a misconfigured nginx server that didn't respond to ipv6 but did for ipv4. For example the .well-known wasn't accessible for that reason on ipv6, but I spent a long time searching for the issue, because wget apparently preferred ipv4 (or automatically tried both).

It would be great if the federation tester would test both ipv4 and ipv6 and report issues for them separately.

**Comment by babolivier** [comment] 2019-05-01 16:49
Hey, thanks for your report! Since the federation does test all IPv6 & IPv4 addresses when computing its connection reports, and you mention the special case of the .well-known, I assume the problem is specific to that request, which happens when trying to look up the available addresses for a homeserver (therefore before generating connection reports), so I've renamed the issue accordingly. Feel free to fix it if you feel like it's a mistake.

**Comment by stygianguest** [comment] 2019-05-04 10:41
Thanks for your reply. You are right that I stated the issue to broadly: it seems you do report results for both ipv4 and ipv6, just not in case of the .well-known info.

**Comment by richvdh** [comment] 2020-07-01 09:40
closing as a dup of #103.

**Closed by richvdh** 2020-07-01 09:40 UTC
