### ISSUE TITLE
fed tester seems to be testing the cert in ip:port instead of hostname:port if .well-known is used

### ISSUE THREAD

**Issue by Bubu** [matrix-org/matrix-federation-tester#23] opened 2019-02-06 13:22 UTC
Example here: https://matrix.org/federationtester/api/report?server_name=bubu1.eu

It should be getting the cert from `matrix.bubu1.eu:443`, instead it connects to `176.9.145.28:443` which has a different cert.

**Comment by turt2live** [comment] 2019-02-06 15:06
Duplicate of https://github.com/matrix-org/matrix-federation-tester/issues/21

**Closed by turt2live** 2019-02-06 15:06 UTC
